// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsomgxggmdmmcosrtfmg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzb21neGdnbWRtbWNvc3J0Zm1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NjIyODksImV4cCI6MjA3MjMzODI4OX0.3WuUv_SKaOcOSwp-UBSonwzp4dRu_k0qvPI-4iWBxM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});